### ISSUE TITLE
I am trying to make i program to play live microphone audio over the live audio out channel but i am having issues

### ISSUE THREAD

**Issue by WolfJack24** [naudio/NAudio#1126]
```csharp
using NAudio.Wave;

class Program
{
    static void Main(string[] args)
    {
        for (int i = -1; i < WaveInEvent.DeviceCount; i++)
        {
            var caps = WaveInEvent.GetCapabilities(i);
            Console.WriteLine($"{i}: {caps.ProductName}");
        }

        Console.WriteLine("Enter the device number of the microphone you want to use:");
        int deviceNumber = Convert.ToInt32(Console.ReadLine());

        var waveIn = new WaveInEvent() { DeviceNumber =  deviceNumber };
        waveIn.WaveFormat = new WaveFormat(44100, 1);

        var bufferedWaveProvider = new BufferedWaveProvider(waveIn.WaveFormat);

        var mixingWaveProvider = new MixingWaveProvider32();
        mixingWaveProvider.AddInputStream(bufferedWaveProvider);

        var waveOut = new WaveOutEvent();
        waveOut.Init(mixingWaveProvider);

        waveIn.DataAvailable += (s, a) =>
        {
            bufferedWaveProvider.AddSamples(a.Buffer, 0, a.BytesRecorded);
        };
        waveIn.StartRecording();

        waveOut.Play();

        Console.WriteLine("Press any key to stop program");
        Console.ReadKey();

        waveIn.StopRecording();
        waveIn.Dispose();
        waveOut.Stop();
        waveOut.Dispose();
    }
}
```
Here is my console app code
and i get the error : 
```
  System.ArgumentException
  HResult=0x80070057
  Message=Must be IEEE floating point Arg_ParamName_Name
  Source=NAudio.Core
  StackTrace:
  at NAudio.Wave.MixingWaveProvider32.AddInputStream(IWaveProvider waveProvider)
  at Program.Main(String[] args) in G:\VSC\Visual Studio (C#)\Audio Layer\Program.cs:line 22
```

any help is accepted

**Comment by mukut1994** [comment]
Hey
In case you're still looking for a solution, it's a really simple fix.

You just need to change 
```
        waveIn.WaveFormat = new WaveFormat(44100, 1);
```

to 
```
        waveIn.WaveFormat = WaveFormat.CreateIeeeFloatWaveFormat(44100, 2);
```

**Comment by markheath** [comment]
The exception is correct: `MixingWaveProvider32` only accepts **32-bit IEEE-float** inputs, but your `BufferedWaveProvider` is fed from `WaveInEvent` at `new WaveFormat(44100, 1)`, which is 16-bit PCM — hence *"Must be IEEE floating point"*.

The suggestion above (setting `waveIn.WaveFormat = WaveFormat.CreateIeeeFloatWaveFormat(...)`) removes *this* error, but it will usually just move the failure: most `waveIn` microphone devices only support 16-bit PCM capture, so requesting IEEE-float typically throws at `StartRecording` on real hardware. It also needlessly switches your mono mic to stereo.

The real point is that you don't need a mixer here at all - there's a single input, so feed it straight to the output:

```csharp
waveIn.WaveFormat = new WaveFormat(44100, 1);            // 16-bit PCM is fine
var bufferedWaveProvider = new BufferedWaveProvider(waveIn.WaveFormat);

var waveOut = new WaveOutEvent();
waveOut.Init(bufferedWaveProvider);                       // no mixer needed

waveIn.DataAvailable += (s, a) =>
    bufferedWaveProvider.AddSamples(a.Buffer, 0, a.BytesRecorded);

waveIn.StartRecording();
waveOut.Play();
```

If you *do* later want to mix several sources, use `MixingSampleProvider`, which is the modern, tested mixer. Let `.ToSampleProvider()` handle the PCM→float conversion for you:

```csharp
var mixer = new MixingSampleProvider(new[] { bufferedWaveProvider.ToSampleProvider() });
// add more inputs with mixer.AddMixerInput(...)
waveOut.Init(mixer);
```

(One thing to watch for a live mic-to-speakers monitor: if the mic and speakers are in the same room you'll get feedback, and you may want to tune `BufferedWaveProvider.BufferDuration` / `DiscardOnBufferOverflow` for latency.)
