### ISSUE TITLE
.Net Maui IOS crashing

### ISSUE THREAD

**Issue by veitan** [naudio/NAudio#1149]
Not finding to much on this.

I keep receiving the error below when trying to open a .net maui app on IOS and then the app terminates. Seems to work fine for me on Android.

[0:] Failed to force load assembly /var/mobile/Containers/Data/Application/86C36058-F0A0-436A-B5C4-775CF63F1D0B/Documents/AudioTesting.content/NAudio.Asio.dll. Type:NAudio.Wave.AsioOut. Exception: 'Object reference not set to an instance of an object.'. Callstack: '   at NAudio.Wave.Asio.AsioDriver.GetAsioDriverNames()
   at NAudio.Wave.AsioOut.GetDriverNames()
   at NAudio.Wave.AsioOut..ctor(Int32 driverIndex)
   at NAudio.Wave.AsioOut..ctor()
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)'

**Comment by veitan** [comment]
Neverminded, I got this figured out. Had my package configuration messed up.
