### ISSUE TITLE
NullReferenceException while disposing WasapiLoopbackCapture

### ISSUE THREAD

**Issue by pedroivobraga** [naudio/NAudio#1183]
I have a MixerProvider capable of mixing loopback and microphone input, with the microphone recording being optional. However, I'm experiencing an intermittent issue when disposing of WasapiLoopbackCapture.

**Into my dispose method, I'm getting the bellow exception:**
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.InteropServices.Marshal.ReleaseComObject(Object o)
   at NAudio.CoreAudioApi.AudioClient.Dispose()
   at NAudio.CoreAudioApi.WasapiCapture.Dispose()
   at EswLinphoneClient.Media.AudioMixerProvider.Dispose

**Dispose method:**

          if (!disposedValue)
          {

              if (disposing)
              {
                  _mixerProvider.RemoveAllMixerInputs();

                  foreach (var source in _mixers.ToArray())
                  {
                      source.Buffer.ClearBuffer();
                      source.Input.Dispose(); //THIS DISPOSE IS CAUSING THE ERROR
                  }

                  _mixers.Clear();

                  _silentPlayer?.Dispose();
                  _timerLoopbackChecker?.Dispose();
                  _timer?.Dispose();
                  _device?.Dispose();
              }

              disposedValue = true;
          }

Do you have any idea that what could be causing such issue?

**Comment by markheath** [comment]
Thanks for the report and apologies for the delayed response. I've been using AI to help me catch up on old NAudio issues...

Here's what's going on.

**Cause**

This is an intermittent double/concurrent dispose of the underlying `IAudioClient` COM wrapper. In NAudio 2, `AudioClient.Dispose()` ends with `Marshal.ReleaseComObject(audioClientInterface)`. The `NullReferenceException` you see isn't a null *argument* (`ReleaseComObject(null)` would throw `ArgumentNullException`) — it's the classic symptom of `ReleaseComObject` being handed a runtime callable wrapper whose underlying COM object has already been released, i.e. it got released twice.

Neither `WasapiCapture.Dispose()` nor `AudioClient.Dispose()` is idempotent or thread-safe — the `if (x != null)` guards are check-then-act, so two threads (or a re-entrant call) can both pass the check and both release. In a mixer setup like yours, `WasapiLoopbackCapture` runs a background capture thread that raises `RecordingStopped` on that thread when there's no `SynchronizationContext`. If the same loopback source is torn down from more than one path — or from inside the `RecordingStopped` handler — you get a second `AudioClient.Dispose()` racing the first. It's intermittent because it depends on that timing.

As a workaround on NAudio 2: make sure each capture is disposed exactly once, from a single thread, and not from within its own `RecordingStopped`/`DataAvailable` handler. Subscribing to `RecordingStopped` and disposing there (rather than disposing inline during your mixer teardown while the capture thread may still be running) avoids the race.

**Status on NAudio 3 (`main`)**

The specific crash is gone. NAudio 3 moved off classic RCWs to source-generated COM interop, so `Marshal.ReleaseComObject` is no longer called anywhere — `AudioClient.Dispose()` now does a guarded `ComObject.FinalRelease()`, and a redundant Dispose is a safe no-op rather than an NRE. The IAudioClient2/3 cross-cast double-free was also fixed as part of that work.

Note this is a "can no longer reproduce this exception" fix rather than fully synchronised disposal — a genuinely concurrent two-thread Dispose is still best avoided. Also, in NAudio 3 `WasapiCapture`/`WasapiLoopbackCapture` are obsolete; the recommended replacement is `WasapiRecorderBuilder`/`WasapiRecorder`.
