### ISSUE TITLE
InvalidOperationException while disposing WaveOutEvent

### ISSUE THREAD

**Issue by pedroivobraga** [naudio/NAudio#1184]
I have a MixerProvider that mixes the loopback and the microphone; however, I'm experiencing an intermittent issue when disposing of the silent playback.

**Into my dispose method, I'm getting the bellow exception:**

System.InvalidOperationException: Handle is not initialized.
   at System.Runtime.InteropServices.GCHandle.Free()
   at NAudio.Wave.WaveOutBuffer.Dispose(Boolean disposing)
   at NAudio.Wave.WaveOutEvent.DisposeBuffers()
   at NAudio.Wave.WaveOutEvent.Dispose()
   at EswLinphoneClient.Media.AudioMixerProvider.Dispose(Boolean disposing) 

Dispose method:

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    _mixerProvider.RemoveAllMixerInputs();

                    foreach (var source in _mixers.ToArray())
                    {
                        source.Buffer.ClearBuffer();
                        //source.Input.Dispose(); Removed because we were experiencing the bellow error:
                        /*
                         Exception Info: System.NullReferenceException
                            at System.Runtime.InteropServices.Marshal.ReleaseComObject(System.Object)
                            at NAudio.CoreAudioApi.AudioClient.Dispose()
                            at NAudio.CoreAudioApi.WasapiCapture.Dispose()
                         */

                    }

                    _mixers.Clear();
                    _silentPlayer?.Dispose();
                }
                disposedValue = true;
            }
        }

Do you have any idea that what could be causing such issue?

**Comment by markheath** [comment]
Apologies for the very delayed response, I'm using AI to help me catch up on some old NAudio issues at the moment...

Thanks for your detailed report — the two stack traces you included actually point at the same underlying cause, which makes this easier to explain.

Both exceptions are a **double-dispose / concurrent-dispose** problem — an object's unmanaged or COM handle is being released twice:

- `WaveOutEvent` → `InvalidOperationException: Handle is not initialized` is `GCHandle.Free()` being called on a handle that was already freed.
- `WasapiCapture` → `NullReferenceException` in `Marshal.ReleaseComObject` is the same thing on the COM side (releasing a COM object that was already released/null).

The good news is that both of these have been hardened in current NAudio. `AudioClient.Dispose()` (the WASAPI/`WasapiCapture` path) is now idempotent and safe against concurrent/re-entrant disposal, and the WinMM `WaveOutBuffer`/`WaveOut` dispose path now guards each handle before freeing it. You're on 1.10.0.0, which predates all of this, so **the first recommendation is to upgrade to the latest 2.2.x release** — that alone should clear both exceptions for the normal (sequential) double-dispose case.

That said, it's worth fixing the dispose pattern in `AudioMixerProvider` too, because the symptoms suggest the lifetime of your sources is a bit tangled:

1. **Dispose each source exactly once, and from one place.** A mixer input, a `WasapiCapture`, and the silent `WaveOutEvent` should each have a single clear owner. The commented-out `source.Input.Dispose()` and the resulting WASAPI NRE strongly suggest a source was being disposed while the mixer (or another path) still referenced it, or disposed twice.
2. **Don't dispose the player from inside its `PlaybackStopped` handler.** If anything in your teardown triggers `PlaybackStopped` while `Dispose` is also running, you get exactly this kind of race. The safe order is: `Stop()` → wait for `PlaybackStopped` → then `Dispose()` once, from a single thread.
3. **Stop capture/playback before tearing down the mixer graph**, so a worker thread isn't still touching a buffer/COM object you're disposing on another thread.
4. Re-introduce `source.Input.Dispose()` once you've upgraded — with the idempotent `AudioClient.Dispose()` in current NAudio, the WASAPI NRE you were working around should no longer occur, and leaving capture devices undisposed will leak them.

If you upgrade and still see either exception with capture/playback fully stopped before disposal and each source disposed exactly once, please reopen with a minimal repro (how the mixer, capture and silent player are wired up and torn down) and we'll dig in further.

For full transparency: the WinMM `WaveOut`/`WaveOutBuffer` guards are safe for sequential double-dispose but aren't hardened against a *truly concurrent* dispose from two threads the way the WASAPI side now is. We're not planning further work there unless we get reports of people still hitting it on a current version with a correct (single-owner, stop-before-dispose) usage pattern — so if that's you, the reproduction details above are exactly what we'd need.
