### ISSUE TITLE
"Not a legal OleAut date" error with playback of long Audiobook

### ISSUE THREAD

**Issue by wykananda** [naudio/NAudio#154]
If an audiobook (m4b) file is longer than 24 hours in length and the AudioFileReader.Position is set anywhere past the 24 hour mark, AudioFileReader.Play will produce the error: "**Not a legal OleAut date**" and the file won't play.

Note that the file will successfully play through and beyond the 24 hour mark while playing continuously. However, attempting to set the Position greater than 24 hours and then playing will cause the above mentioned error to occur. 

This also occurs after setting the AudioFileReader.CurrentTime to a Timespan > 24 hours (1 day or greater). 

Unfortunately, this makes the NAudio component unusable for an audiobook application. :(

My guess is that this error would affect other formats too but I don't have one that long handy at the moment.

**Comment by markheath** [comment]
have you got a stack trace for the exception?

Setting position on a `MediaFoundationReader` results in a call to [IMFSourceReader::SetCurrentPosition](https://msdn.microsoft.com/en-us/library/windows/desktop/dd374668(v=vs.85).aspx), so there might be an issue there.

**Comment by wykananda** [comment]
Hi. The failure seems to occur when marshalling the PropVariant just before
the SetCurrentPosition call.  Changing the PropVariant.date type from
DateTime to double seems to be the cure.

//previously a DateTime but needs to be an OLE Automation Date type
(double)
//or will fail when the DateTime is >= 1/2/0001 12:00:00 AM (24 hours)
[FieldOffset(8)] private *double *date;

System.OverflowException was unhandled
  HResult=-2146233066
  Message=Not a legal OleAut date.
  Source=mscorlib
  StackTrace:
       at System.Runtime.InteropServices.Marshal.StructureToPtr(Object
structure, IntPtr ptr, Boolean fDeleteOld)
       at NAudio.Wave.MediaFoundationReader.Reposition(Int64
desiredPosition) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\WaveStreams\MediaFoundationReader.cs:line
336
       at NAudio.Wave.MediaFoundationReader.Read(Byte[] buffer, Int32
offset, Int32 count) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\WaveStreams\MediaFoundationReader.cs:line
220
       at
NAudio.Wave.SampleProviders.Pcm16BitToSampleProvider.Read(Single[] buffer,
Int32 offset, Int32 count) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\SampleProviders\Pcm16BitToSampleProvider.cs:line
31
       at NAudio.Wave.SampleProviders.MeteringSampleProvider.Read(Single[]
buffer, Int32 offset, Int32 count) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\SampleProviders\MeteringSampleProvider.cs:line
70
       at NAudio.Wave.SampleProviders.VolumeSampleProvider.Read(Single[]
buffer, Int32 offset, Int32 sampleCount) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\SampleProviders\VolumeSampleProvider.cs:line
40
       at NAudio.Wave.SampleProviders.SampleChannel.Read(Single[] buffer,
Int32 offset, Int32 sampleCount) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\SampleProviders\SampleChannel.cs:line 56
       at NAudio.Wave.AudioFileReader.Read(Single[] buffer, Int32 offset,
Int32 count) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\WaveStreams\AudioFileReader.cs:line 122
       at NAudio.Wave.AudioFileReader.Read(Byte[] buffer, Int32 offset,
Int32 count) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\WaveStreams\AudioFileReader.cs:line 107
       at NAudio.Wave.SampleProviders.WaveToSampleProvider.Read(Single[]
buffer, Int32 offset, Int32 count) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\SampleProviders\WaveToSampleProvider.cs:line
31
       at
NAudio.Wave.SampleProviders.MonoToStereoSampleProvider.Read(Single[]
buffer, Int32 offset, Int32 count) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\SampleProviders\MonoToStereoSampleProvider.cs:line
47
       at NAudio.Wave.SampleProviders.MeteringSampleProvider.Read(Single[]
buffer, Int32 offset, Int32 count) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\SampleProviders\MeteringSampleProvider.cs:line
70
       at NAudio.Wave.SampleProviders.VolumeSampleProvider.Read(Single[]
buffer, Int32 offset, Int32 sampleCount) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\SampleProviders\VolumeSampleProvider.cs:line
40
       at NAudio.Wave.SampleProviders.SampleChannel.Read(Single[] buffer,
Int32 offset, Int32 sampleCount) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\SampleProviders\SampleChannel.cs:line 56
       at NAudio.Wave.SampleProviders.MeteringSampleProvider.Read(Single[]
buffer, Int32 offset, Int32 count) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\SampleProviders\MeteringSampleProvider.cs:line
70
       at NAudio.Wave.SampleProviders.SampleToWaveProvider.Read(Byte[]
buffer, Int32 offset, Int32 count) in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\SampleProviders\SampleToWaveProvider.cs:line
35
       at NAudio.Wave.WaveOutBuffer.OnDone() in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\WaveStreams\WaveOutBuffer.cs:line 105
       at NAudio.Wave.WaveOut.EnqueueBuffers() in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\WaveOutputs\WaveOut.cs:line 160
       at NAudio.Wave.WaveOut.Play() in C:\Dev\Visual
Studio\Library\NAudio\NAudio\Wave\WaveOutputs\WaveOut.cs:line 148
       at
NAudioDemo.AudioPlaybackDemo.AudioPlaybackPanel.OnButtonPlayClick(Object
sender, EventArgs e) in C:\Dev\Visual
Studio\Library\NAudio\NAudioDemo\AudioPlaybackDemo\AudioPlaybackPanel.cs:line
72
       at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key,
EventArgs e)
       at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
       at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
       at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
       at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons
button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ToolStrip.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd,
Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG&
msg)
       at
System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr
dwComponentID, Int32 reason, Int32 pvLoopData)
       at
System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32
reason, ApplicationContext context)
       at
System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason,
ApplicationContext context)
       at NAudioDemo.Program.Main() in C:\Dev\Visual
Studio\Library\NAudio\NAudioDemo\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly,
String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence
assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by markheath** [comment]
ok, that makes sense. Will try to get that changed assuming it doesn't conflict with any other NAudio features

**Comment by markheath** [comment]
may be better to simply comment out `PropVariant.date`
