### ISSUE TITLE
Exception on playing Spotify Song Preview URL

### ISSUE THREAD

**Issue by eyanson** [naudio/NAudio#240]
I am testing library using your test app.
Load MP3 Stream option.
Put this URL: https://p.scdn.co/mp3-preview/63c396837c1738dd17a7a2b055a4981dce74f46f?cid=26d287105e31491889f3cd293d85bfea

This URL is a song preview from Spotify API.
If I put the URL in google chrome, the song play ok, but not in your app.

After 10 seconds I get this error:

System.ArgumentNullException was unhandled
  HResult=-2147467261
  Message=You must provide a non-null Mp3Frame to decompress
Parameter name: frame
  ParamName=frame
  Source=NAudio
  StackTrace:
       at NAudio.Wave.AcmMp3FrameDecompressor.DecompressFrame(Mp3Frame frame, Byte[] dest, Int32 destOffset) in C:\Users\eyanson\Downloads\NAudio-master\NAudio-master\NAudio\FileFormats\Mp3\Mp3FrameDecompressor.cs:line 52
       at NAudioDemo.Mp3StreamingDemo.Mp3StreamingPanel.StreamMp3(Object state) in C:\Users\eyanson\Downloads\NAudio-master\NAudio-master\NAudioDemo\Mp3StreamingDemo\MP3StreamingPanel.cs:line 118
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
  InnerException:

**Comment by markheath** [comment]
looks like a bug where frame is null, we shouldn't try to decompress it. I've made a small fix.
