### ISSUE TITLE
Windows 7 x86 StreamMediaFoundationReader error

### ISSUE THREAD

**Issue by kellyelton** [naudio/NAudio#274]
Trying to read the file [800hzBeep.zip](https://github.com/naudio/NAudio/files/1530139/800hzBeep.zip) results in the following error in Windows 7 x86

    System.Runtime.InteropServices.COMException (0xC00D36C4): Exception from HRESULT: 0xC00D36C4
        at NAudio.MediaFoundation.MediaFoundationInterop.MFCreateSourceReaderFromByteStream(IMFByteStream pByteStream, IMFAttributes pAttributes, IMFSourceReader& ppSourceReader)
        at NAudio.Wave.StreamMediaFoundationReader.CreateReader(MediaFoundationReaderSettings settings)
        at NAudio.Wave.MediaFoundationReader.Init(MediaFoundationReaderSettings initialSettings)
        at NAudio.Wave.StreamMediaFoundationReader..ctor(Stream stream, MediaFoundationReaderSettings settings)
        at Traxcore.AudioPlayerFacade.InitializeWaveStream(Stream audioStream)

The Code

    private WaveStream InitializeWaveStream(Stream audioStream) {
        // Loads the audio stream into a reader that can read the audio data from it.
        return new StreamMediaFoundationReader(audioStream);
    }

I also load the audio file using WPF

    LoadSound(new Uri("Resources/Sounds/800hzBeep.wav"));
    public AudioPlayerFacade LoadSound(Uri source) {
        StreamResourceInfo info = Application.GetRemoteStream(source);

        var audio = new AudioPlayerFacade();
        audio.InitializeWaveStream(info.Stream);
        return audio;
    }

**Comment by kellyelton** [comment]
After some testing, it appears to be related to how the file was saved. If you open the file in Audacity and reexporting it in the same format, it works fine.
