### ISSUE TITLE
Cannot play AIF file

### ISSUE THREAD

**Issue by sonic414** [naudio/NAudio#31]
I got an exception playing the file sample.aif from http://www.nch.com.au/acm/formats.html

System.ArgumentOutOfRangeException was caught
  HResult=-2146233086
  Message=Non-negative number required.
Parameter name: count
  Source=mscorlib
  ParamName=count
  StackTrace:
       at System.IO.BinaryReader.ReadBytes(Int32 count)
       at NAudio.Wave.AiffFileReader.ReadAiffHeader(Stream stream, WaveFormat& format, Int64& dataChunkPosition, Int32& dataChunkLength, List`1 chunks) in j:\Samples\Media\NAudio-master\NAudio-master\NAudio\Wave\WaveStreams\AiffFileReader.cs:line 108
       at NAudio.Wave.AiffFileReader..ctor(Stream inputStream) in j:\Samples\Media\NAudio-master\NAudio-master\NAudio\Wave\WaveStreams\AiffFileReader.cs:line 41
       at NAudio.Wave.AiffFileReader..ctor(String aiffFile) in j:\Samples\Media\NAudio-master\NAudio-master\NAudio\Wave\WaveStreams\AiffFileReader.cs:line 28

I got it working by changing the code in AiffFileReader @ 108 to 
  else
                {
                    if (chunks != null)
                    {
                        chunks.Add(nextChunk);
                    }
+                    if (br.BaseStream.Position + nextChunk.ChunkLength < br.BaseStream.Length)
                        br.ReadBytes((int)nextChunk.ChunkLength);
                }

But I'm not sure this is the right way.

**Comment by sonic414** [comment]
The link to the file is http://www.nch.com.au/acm/sample.aif

**Comment by sonic414** [comment]
Sorry, Accidentally hit "Close and comment" 

The link to the sound file is 
http://www.nch.com.au/acm/sample.aif

**Comment by sonic414** [comment]
Also, this exception exits out without properly disposing the BinaryReader. Shoudn't the method have a try catch "finally" block?

**Comment by markheath** [comment]
the BinaryReader shouldn't be disposed or it will dispose the underlying stream which we don't want. But I've resolved the issue reported
