### ISSUE TITLE
GCThread Exception after AcmStream.Dispose()

### ISSUE THREAD

**Issue by mail4andrey** [naudio/NAudio#355]
After Dispose() for AcmStream:

`  public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
`
 and something wrong/exception in this part
`            if (streamHandle != IntPtr.Zero)
            {
                MmResult result = AcmInterop.acmStreamClose(streamHandle, 0);
                streamHandle = IntPtr.Zero;
                if (result != MmResult.NoError)
                {
                    throw new MmException(result, "acmStreamClose");
                }
            }`

Now I have `System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at NAudio.Wave.Compression.AcmInterop.acmStreamClose(IntPtr hAcmStream, Int32 closeFlags)
   at NAudio.Wave.Compression.AcmStream.Dispose(Boolean disposing)
   at NAudio.Wave.AcmMp3FrameDecompressor.Dispose()
   at NAudio.Wave.Mp3FileReader.Dispose(Boolean disposing)
   at System.IO.Stream.Close()`.

After that I skip part with `GC.SuppressFinalize(this);` and in GC thread have `NAudio.MmException: InvalidHandle calling acmStreamClose
   at NAudio.Wave.Compression.AcmStream.Dispose(Boolean disposing)
   at NAudio.Wave.Compression.AcmStream.Finalize() `

https://github.com/naudio/NAudio/blob/e359ca0566e9f9b14fee1ba6e0ec17e4482c7844/NAudio/Wave/Compression/AcmStream.cs

**Comment by markheath** [comment]
I'm not sure exactly what the issue is here. Do you have a simple way to reproduce your problem with the current NAudio code?

**Comment by mail4andrey** [comment]
https://github.com/mail4andrey/NAudio/commit/cbf68c6cbdce60875d3a5908096fdc1878416210
I try to add this situation to test. But it is slightly different. When we second time dispose AcmStream (from destructor) should be MmException with message "InvalidHandle".

For mock function of dll I use JustMock.

**Comment by markheath** [comment]
Thanks for the detailed report — your diagnosis was correct. Two fixes have landed on the `naudio3dev` branch (slated for the NAudio 3 release):

- **`350a189`** — defensive fix in `AcmStream.Dispose`: clear `streamHandle` / `driverHandle` **before** the native close, so an AV in `acmStreamClose` can no longer leave the field set for the finalizer to re-close. This removes the `MmException: InvalidHandle` follow-on you saw on the GC thread.
- **`b7e19af`** — underlying cause: `msacm32.dll` is not thread-safe. Concurrent ACM calls from multiple threads (including finalizer-thread closes racing app-thread opens, which is the most likely setup for what you hit) corrupt internal driver state and produce native AVs. Every msacm32 P/Invoke in `AcmInterop` now serialises through a single static lock. The lock is reentrant (`Monitor`), so msacm32 callbacks (`acmDriverEnum` etc.) still work.

We reproduced the AV reliably under load (~10 s to crash without the fix) and confirmed both commits eliminate it.
