### ISSUE TITLE
NAudio device enumeration stops working when combined with AudioSwitcher

### ISSUE THREAD

**Issue by MortInfinite** [naudio/NAudio#421]
With NAudio  commit 420e607 or NAudio NuGet version 1.8.5, I receive the following exception, when trying to create a new instance of MMDeviceEnumerator.

> System.InvalidCastException: 'Unable to cast object of type 'System.__ComObject' to type 'NAudio.CoreAudioApi.Interfaces.MMDeviceEnumeratorComObject'.'

The problem occurs if calling the following code:

```
var coreAudioController = new AudioSwitcher.AudioApi.CoreAudio.CoreAudioController();
var deviceEnumerator = new NAudio.CoreAudioApi.MMDeviceEnumerator();
```

The problem does not occur if calling the following code:
```
var deviceEnumerator = new NAudio.CoreAudioApi.MMDeviceEnumerator();
```

It appears that AudioSwitcher interferes with the creation of the NAudio.CoreAudioApi.Interfaces.MMDeviceEnumeratorComObject object that NAudio uses for device enumeration.

Since this problem only occurs when using both AudioSwitcher (Version 3.0.0) and NAudio, I don't know if this is the correct place to report the problem or if I should post it in the [AudioSwitcher](https://github.com/xenolightning/AudioSwitcher) project.

**Comment by markheath** [comment]
Hmm, not sure why that might be happening. Feel free to ask over at AudioSwitcher to see if they can explain what's going on.

**Comment by XySoftNeil** [comment]
The work around is to use the AudioSwitcher CoreAudioController members/methods instead. GetPlaybackDevices, and DefaultPlaybackDevice, etc.

**Comment by MultiverseBoy** [comment]
Same problem here. Tried to use another library CSCore instead of NAudio, the same problem shows.
So I assume the problem is AudioSwitcher.
I need AudioSwitcher to set the default devices. And the NAudio to do the detail settings, thought it would work. Bad luck.

**Comment by snippyy** [comment]
Same problem but i solved it. The AudioSwitcher.AudioApi.CoreAudio has conflict with NAudio.CoreAudioApi, you need to switch the order.

**Comment by MortInfinite** [comment]
> Same problem but i solved it. The AudioSwitcher.AudioApi.CoreAudio has conflict with NAudio.CoreAudioApi, you need to switch the order. set the AudioSwitcher.AudioApi.CoreAudio under the NAudio.CoreAudioApi.

I stopped using NAudio, so I can't check if the workaround solves the problem for me, but I hope your suggestion can help others.

**Comment by KWB** [comment]
@snippyy Same problem here, but what exactly do you mean by "set the AudioSwitcher.AudioApi.CoreAudio under the NAudio.CoreAudioApi."

Can you give me a hint please.

**Comment by markheath** [comment]
I am currently using AI to help catch review the backlog of open issues, and so closing this with a brief summary...

This isn't an NAudio defect — it's a COM activation/apartment interaction between NAudio and AudioSwitcher, which both wrap the same Windows Core Audio `MMDeviceEnumerator` COM object. The tell-tale signs: it only happens when `AudioSwitcher.AudioApi.CoreAudio.CoreAudioController` is constructed in the same process, it's sensitive to the order the two are created (multiple people in this thread fixed it purely by reordering), and `@MultiverseBoy` reproduced the identical failure with a completely different library (CSCore) plus AudioSwitcher. A bug inside one library doesn't depend on the construction order of an unrelated third-party library.

Two practical points:

1. **Workaround on older NAudio (1.x/2.x):** construct `new NAudio.CoreAudioApi.MMDeviceEnumerator()` *before* you construct the AudioSwitcher `CoreAudioController` (some users report the opposite order works in their environment — try both). This is what several people in the thread confirmed works.

2. **NAudio 3:** the internal activation path that produced the exact `InvalidCastException` quoted here (`...Interfaces.MMDeviceEnumeratorComObject`) has been rewritten. NAudio 3 no longer uses the legacy `[ComImport]` coclass + RCW-cast pattern; it activates the enumerator via `CoCreateInstance` projected through `ComWrappers`, and the `MMDeviceEnumeratorComObject` type the error references no longer exists. So this specific exception should not occur on NAudio 3.

Given the original reporter has moved off NAudio, the workaround is documented above, and the underlying mechanism has been removed in NAudio 3, I'm going to close this. If you hit a *new* device-enumeration failure specifically on NAudio 3 (with or without AudioSwitcher), please open a fresh issue with the NAudio 3 version, a minimal repro, and the full exception/stack trace.

**Comment by simplifirepyroneil** [comment]
I explored this again, and  it seems that using the device inside the MMDeviceEnumerator's using scope is a problem.  Specifically the Getting of the AudioEndPointVolumr.MasterVolumeLevelScalar.

The below code works. Move the line where volume is used inside the using, and it throws the exception. 
I will look at the MMDeviceEnumerator and see what it does when it frees up resources.     

try
      {
         using(MMDeviceEnumerator mmDeviceEnumerator = new MMDeviceEnumerator())
         {
            device = mmDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow.Render, Role.Multimedia);
         }
         // **make dang sure this is not inside the enumerator scope above.**
         device.AudioEndpointVolume.OnVolumeNotification += AudioEndpointVolume_OnVolumeNotification;
         Muted = device.AudioEndpointVolume.Mute;
         Volume = device.AudioEndpointVolume.MasterVolumeLevelScalar;
      }
      catch(Exception ex)
      {
         log.Error($"Audio: Could not get default audio endpoint - {ex.GetBaseException().Message}");
      }

**Comment by markheath** [comment]
thanks for the info, will look into that. Which version of NAudio are you testing against?

**Comment by simplifirepyroneil** [comment]
NAudio v 2.3.0,  .NET 10,  Windows 10. 
I will try testing on Windows 11 and will comment if the problem clears up on 11.

**Comment by markheath** [comment]
I tried reproducing your issue with NAudio 2.3.0 on Windows 11 but works fine for me. What exception did you get?

**Comment by simplifirepyroneil** [comment]
This code  below shows the complete setup to throw the exception..  The code is running in the UI thread, Constructor called when initializing a  property. 

```
   private readonly MMDevice device;
   public MMDevice Device { get => device; }

   protected NAudioEngine()
   {
         using(MMDeviceEnumerator mmDeviceEnumerator = new MMDeviceEnumerator())
         {
            device = mmDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow.Render, Role.Multimedia);

            Muted = device.AudioEndpointVolume.Mute;
            Volume = device.AudioEndpointVolume.MasterVolumeLevelScalar;
            device.AudioEndpointVolume.OnVolumeNotification += AudioEndpointVolume_OnVolumeNotification;
         }
...
}
--------------------------------------------------------
System.InvalidCastException: Unable to cast object of type 'NAudio.CoreAudioApi.Interfaces.MMDeviceEnumeratorComObject' to type 'CoreAudio.CMMDeviceEnumerator'.

   at CoreAudio.MMDeviceEnumerator..ctor(Guid eventContext)
   at CoreAudio.MMDeviceEnumerator..ctor()

InnerException - null
HResult -2147467262

Windows Event Viewer - Nothing relating to COM or audio logged
Sound Settings - RealTek High Definition Audio - driver 6.0.1.7560 from 7/15/2015
```

If this is a "no" priority its no problem. I have a workaround. Thanks for saving me so much time and grief by creating NAudio. It makes life so much easier!

**Comment by markheath** [comment]
Ah OK,  you usually see that invalid cast exception is when the COM object gets accessed on a different thread from the one that created it. Not completely sure how that happens on your example (still haven't managed to reproduce it). But it's something I'm hoping the new approach to COM interop in NAudio 3 will help with.

**Comment by markheath** [comment]
Also, you're using `CoreAudio.MMDeviceEnumerator` - which is not NAudio - that's a different project. I imagine you're getting some kind of clash by trying to use both libraries at the same time. So it's probably not a threading issue - it's whichever library happens to activate the COM object first. 

NAudio 3 still might be able to help with this as it doesn't use ComImport
