### ISSUE TITLE
WasapiLoopbackCapture throws COMException(0x8889000F)

### ISSUE THREAD

**Issue by eigoninaritai-naokichi** [naudio/NAudio#453]
I use WasapiLoopbackCapture class and WasapiLoopbackCapture.StartRecording(). When I call the method, it throws below:
```
Unhandled Exception: System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x8889000F
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at NAudio.CoreAudioApi.WasapiCapture.InitializeCaptureDevice()
   at NAudio.CoreAudioApi.WasapiCapture.StartRecording()
   at SpeakerTest.Program.Main(String[] args) in C:\Develop\SpeakerTest\SpeakerTest\Program.cs:line 19
```

The source code is below:
```
public class Program
{
   public static void Main(string[] args)
   {
      using (var speaker = new WasapiLoopbackCapture(new MMDeviceEnumerator().GetDefaultAudioEndpoint(DataFlow.Render, Role.Console)))
      {
         speaker.DataAvailable += new EventHandler<NAudio.Wave.WaveInEventArgs>(Program.SpeakerEvent);
         speaker.StartRecording();
         speaker.StopRecording();
      }
      Console.ReadKey();
   }

   private static void SpeakerEvent(object sender, WaveInEventArgs e)
   {
   }
}
```

How can I solve this problem? Do you have any idea? Also I use NAudio version 1.8.4.

**Comment by markheath** [comment]
This is AUDCLNT_E_ENDPOINT_CREATE_FAILED. "The method failed to create the audio endpoint for the render or the capture device. This can occur if the audio endpoint device has been unplugged, or the audio hardware or associated hardware resources have been reconfigured, disabled, removed, or otherwise made unavailable for use"
