### ISSUE TITLE
Intermittent issue when playing sound using Waveout

### ISSUE THREAD

**Issue by PankajLala** [naudio/NAudio#524]
Note: 
I am using Waveout initialized with a WaveStream to play an mp3 sound. 
When playing the waveout, Intermittently I have noticed the following error in the logs. It causes the sound not play.
"NAudio.MmException: NoDriver calling waveOutWrite
   at NAudio.Wave.WaveOutBuffer.WriteToWaveOut()
   at NAudio.Wave.WaveOutBuffer.OnDone()
   at NAudio.Wave.WaveOut.EnqueueBuffers()
   at NAudio.Wave.WaveOut.Play()

I have not been able to replicate the issue, any pointers in right directions are appreciated.

**Comment by markheath** [comment]
maybe attempting to play to a USB device that has been removed?

**Comment by markheath** [comment]
Closing this as it's an old issue. In NAudio 3 I'd recommend using `WasapiPlayer` instead
