### ISSUE TITLE
"AcmNotPossible calling acmFormatSuggest" Exception initialziing AudioFileReader with .wav file

### ISSUE THREAD

**Issue by mikemorton** [naudio/NAudio#526]
I have a specific .wav file that I'm trying to load into an AudioFileReader using `new AudioFileReader(filePath);`

However when I call the AudioFileReader constructor with the file path and exception is thrown: 
> AcmNotPossible calling acmFormatSuggest

Call Stack: 

>    at NAudio.Wave.Compression.AcmStream.SuggestPcmFormat(WaveFormat compressedFormat)
   at NAudio.Wave.WaveFormatConversionStream.CreatePcmStream(WaveStream sourceStream)
   at NAudio.Wave.AudioFileReader.CreateReaderStream(String fileName)
   at NAudio.Wave.AudioFileReader..ctor(String fileName)
   at (my code here)...

I'm running version 1.8.5, but I did test updating to the latest and didn't see any resolution.

**Comment by markheath** [comment]
it means your WAV file is using a codec that there is no support for in your version of Windows. To see the format in use,  open the WAV file with `WaveFileReader` and examine the `WaveFormat` property

**Comment by mikemorton** [comment]
Thanks for the speedy response, I'll give that a try!

**Comment by mikemorton** [comment]
@markheath it looks like the format is MpegLayer3 which I guess means the wav file is essentially an mp3?  Do you know a reliable and legal place to obtain the codec needed to decode this file?

**Comment by markheath** [comment]
depends what version of Windows you have. On consumer windows there always used to be an MP3 ACM, but not on server windows. (but you could enable the "Desktop Experience"). Can't remember off the top of my head whether Windows 10 includes the MP3 ACM codec.

**Comment by mikemorton** [comment]
I'm using windows 10.   I found my way to your blog (https://markheath.net/post/nodriver-calling-acmformatsuggest) where one of the suggestions was to use MediaFoundationReader - this let me move forward with initalizing the WaveStream which I can use to call ToSampleProvider which is my end goal.  

However I'm finding that the `TotalTime` in the file is not correct even though all of the other info in the MediaFoundationReader instance is correct, as verified in Audacity. 🤔

**Comment by mikemorton** [comment]
I think my latest issue is the same as the one here: https://github.com/naudio/NAudio/issues/467

I'm not quite understanding the solution provided there though.

**Comment by markheath** [comment]
`MediaFoundationReader` relies on the Media Foundation APIs, so NAudio has no control over what it reports as the total time unfortunately. I guess in your case another option would be to use `WaveFileReader` to extract the data into an MP3 file and then just use `Mp3FileReader` from then on
