### ISSUE TITLE
Windows 10 Mobile ole32.dll error when playing

### ISSUE THREAD

**Issue by juanpaexpedite** [naudio/NAudio#59]
Hello, I suppose you know about this issue, tested on the latest release of Mobile:

Unable to load DLL 'ole32.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E):
When play a file,  variant.Clear(); calls to 

public void Clear()
        {
            PropVariantClear(ref this);
        }

        [DllImport("ole32.dll")]
        private static extern int PropVariantClear(ref PropVariant pvar);

what is not available on Mobile, I understand.

**Comment by czesiu** [comment]
I have the same error on Raspberry Pi on Windows Universal Sample.

Here is the full stack trace:
    
    Unable to load DLL 'ole32.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
    at NAudio.CoreAudioApi.Interfaces.PropVariant.PropVariantClear(PropVariant& pvar)
    at NAudio.CoreAudioApi.Interfaces.PropVariant.Clear()
    at NAudio.Wave.MediaFoundationReader.GetLength(IMFSourceReader reader)
    at NAudio.Wave.MediaFoundationReader..ctor(String file, MediaFoundationReaderSettings settings)
    at NAudioUniversalDemo.MediaFoundationReaderUniversal..ctor(MediaFoundationReaderUniversalSettings settings)
    at NAudioUniversalDemo.MediaFoundationReaderUniversal..ctor(IRandomAccessStream stream)
    at NAudioUniversalDemo.MainPageViewModel.CreateReader()
    at NAudio.Win8.Wave.WaveOutputs.WasapiOutRT.Init()
    at NAudio.Win8.Wave.WaveOutputs.WasapiOutRT.<PlayThread>d__25.MoveNext()```

**Comment by kamenlitchev** [comment]
Seems like another DLL reference that needs to be changes. As per https://msdn.microsoft.com/en-us/library/windows/desktop/hh802935(v=vs.85).aspx#api_sets_available_in_windows_10 the PropVariantClear seems to be placed in "api-ms-win-core-com-l1-1-1.dll"

**Comment by juanpaexpedite** [comment]
kamenlitchev You are totally right! changing to:

[DllImport("api-ms-win-core-com-l1-1-1.dll")]
private static extern int PropVariantClear(ref PropVariant pvar);

works both on mobile and desktop, 
czesiu  would you try on Raspberry Pi?

**Comment by czesiu** [comment]
I checked and it works on Raspberry Pi

**Comment by BarryOCathain** [comment]
> I checked and it works on Raspberry Pi

Just so I'm clear, is that IoT on the pi?
