### ISSUE TITLE
Resampling audio occassionally causes "System.AccessViolationException" and crashes app

### ISSUE THREAD

**Issue by ththiem** [naudio/NAudio#629]
Hello,

We've been using NAudio for a couple years now to resample raw audio bytes in realtime in-memory and recently we have started seeing this particular issue come up in the resampling process that is crashing our service. We resample simply like thus:

```
     var output = new MemoryStream();
     using (var reader = new WaveFileReader(new MemoryStream(byteArray)))
     {
         using (var convertedStream = WaveFormatConversionStream.CreatePcmStream(reader))
         {
             WaveFileWriter.WriteWavFileToStream(output, convertedStream);
             return Task.FromResult(output);
         }
     }
```

Our source audio is 8-bit, 8khz Mulaw audio and we're converting to 16-bit, 16khz PCM. This typically works most of the time, but under load the service may randomly cause this for no explicable reason. I can even reproduce it locally when just rerunning a few sample audio files as input over and over again until it eventually happens:

```
An unhandled exception of type 'System.AccessViolationException' occurred in NAudio.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt. occurred
```

Any idea as to what's causing this?

**Comment by ththiem** [comment]
A simple console app I wrote was able to reproduce this with enough concurrent threads:
`Fatal error. 
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at NAudio.Wave.Compression.AcmInterop.acmStreamClose(IntPtr, Int32)
   at NAudio.Wave.Compression.AcmInterop.acmStreamClose(IntPtr, Int32)
   at NAudio.Wave.Compression.AcmStream.Dispose(Boolean)
   at NAudio.Wave.WaveFormatConversionProvider.Dispose(Boolean)
   at NAudio.Wave.WaveFormatConversionStream.Dispose(Boolean)
   at System.IO.Stream.Close()
   at ConsoleTest.Speech.Helper.ConvertAudioFormat(System.IO.MemoryStream, System.String)
   at ConsoleTest.Speech.Speech+<GetFileStream>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at ConsoleTest.Speech.Speech.GetFileStream(System.String)
Finished 3896
   at ConsoleTest.Speech.Speech+<ResampleStream>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at ConsoleTest.Speech.Speech.ResampleStream(System.String)
   at ConsoleTest.Speech.Speech+<ResampleFiles>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at ConsoleTest.Speech.Speech.ResampleFiles(Int32)
   at ConsoleTest.Program+<>c.<Speech2>b__13_0(Int32)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica.Execute()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

**Comment by ththiem** [comment]
Here's a little more information I was able to get, but otherwise I have no way to solve or prevent this issue from happening in our production servers unfortunately. I don't know of any alternatives or methods to do this particular resampling process so I'm looking at mitigating it through other means (restart and recovery).

`Exception thrown at 0x00007FF8D6C25E2C (msacm32.dll) in ConsoleTest.exe: 0xC0000005: Access violation reading location 0x000000002EBFD3FC (random location). occurred`

Here's a minidump from VS2019 as well if anyone finds that useful:
https://drive.google.com/file/d/1SGhLExlYW4-XUKWLvjpKBt05rMoqjQUE/view?usp=sharing

**Comment by highspeeder** [comment]
Whenever I use acmstream-related class, the same exception occurs, too.

**Comment by markheath** [comment]
thanks for reporting. This error is usually a sign that something that ought to be pinned (so the garbage collector can't move it) isn't being. Having said that, the ACM classes have been stable and reliable for many years so am a little surprised to see it breaking now. NAudio does have a fully managed mu-law decoder, so in your case you could use that

**Comment by markheath** [comment]
Confirmed and fixed — thanks for the clear repro and the minidump. The root cause is that `msacm32.dll` is not thread-safe: concurrent ACM calls from multiple threads (which `Parallel.For` over `WaveFormatConversionStream.CreatePcmStream` is exactly) corrupt internal driver state and produce the AV you saw at `acmStreamClose`.

We reproduced your scenario directly (parallel mu-law → PCM under load crashed in ~10 s) and confirmed the fix runs clean indefinitely.

Two commits on the `naudio3dev` branch (slated for NAudio 3):

- **`b7e19af`** — every msacm32 P/Invoke in `AcmInterop` now serialises behind a single static lock. ACM is therefore effectively single-threaded process-wide — for high-throughput resampling/conversion consider Media Foundation or DMO (`MediaFoundationResampler` is the closest equivalent for your mu-law → PCM case). XML doc remarks on `AcmStream` and `AcmDriver` flag this.
- **`350a189`** — separate latent bug surfaced by the investigation: `AcmStream.Dispose` was leaving `streamHandle` non-zero if the close threw or AV'd, letting `~AcmStream` double-close on the finalizer thread. Now zeroed before the close.

**Comment by markheath** [comment]
Closing this as is available in the NAudio 3 preview releases now
