### ISSUE TITLE
Exception in WasapiOutRT.Activate (FileNotFoundException)

### ISSUE THREAD

**Issue by jtorjo** [naudio/NAudio#743]
I keep getting this on customer's machines, probably, 1 out of 40-50 machines.
I don't understand how this can happen, since I play using only internal in-memory buffers.

The exception I get in release, is this:

    FATAL - App crash: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    at NAudio.Wave.WasapiOutRT.Activate()
    at NAudio.Wave.WasapiOutRT.PlayThread()
    at Windows.ApplicationModel.Core.UnhandledError.Propagate()
    at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
    --- End of stack trace from previous location where exception was thrown ---
    at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, UnhandledErrorDetectedEventArgs eventArgs)

I did look at the implementation for WasapiOutRT.Activate(), and all I can think of is that some of the code called by some other lib will throw this. It kind of makes 

Can this somehow be related to the user not having Media Player installed?

**Comment by markheath** [comment]
Not sure, I still consider WasapiOutRT to be experimental - have never used it in anger myself. What sort of app are you building?

**Comment by markheath** [comment]
`WasapiOutRT` was part of the UWP/WinRT-specific `NAudio.Uap` assembly, which has been retired in NAudio 3 and won't be carried forward. The class no longer exists, so this crash path is gone.

If you're moving to NAudio 3, the replacement for `WasapiOutRT` is `WasapiPlayer` (built via `WasapiPlayerBuilder`) - a modern, zero-copy, async player that supersedes the old RT classes.

For the record, the original `FileNotFoundException (0x80070002)` you saw was most likely WinRT MediaFoundation activation failing on machines lacking the Media Feature Pack (Windows N/KN editions), which fits it only appearing on a small fraction of machines - but that's no longer relevant with the RT classes removed.
