### ISSUE TITLE
MediaFoundationResampler "The callee is currently not accepting further input"

### ISSUE THREAD

**Issue by Vivelin** [naudio/NAudio#840]
I am using the MediaFoundationResampler to resample audio on-the-fly so I can concatenate multiple audio sources into a single provider.

I figured out that to provide fast seeking, I need to call **Reposition()** on the MediaFoundationResampler. This seems to work fine.

Seeking too much, too quickly, however, seems to throw a COM exception:

> System.Runtime.InteropServices.COMException (0xC00D36B5): The callee is currently not accepting further input. (0xC00D36B5)
   at NAudio.MediaFoundation.IMFTransform.ProcessInput(Int32 dwInputStreamId, IMFSample pSample, Int32 dwFlags)
   at NAudio.MediaFoundation.MediaFoundationTransform.Read(Byte[] buffer, Int32 offset, Int32 count)
   at NAudio.Wave.SampleProviders.WaveToSampleProvider.Read(Single[] buffer, Int32 offset, Int32 count)
   [...]

This seems to be something you expected, as [MediaFoundationTransform.cs](https://github.com/naudio/NAudio/blob/master/NAudio.Wasapi/MediaFoundation/MediaFoundationTransform.cs#L144) shows:

```csharp
// give the input to the resampler
// can get MF_E_NOTACCEPTING if we didn't drain the buffer properly
transform.ProcessInput(0, sample, 0);
```

I'm not entirely sure what I could do about this from my end. The WdlResamplingSampleProvider seems to be working just fine for me so I can continue my work, but I figured this was worth reporting.

**Comment by markheath** [comment]
This was a flush/drain bug in the MFT reposition path: Media Foundation transforms require all pending output to be drained before more input is accepted, and a flush on seek — the old `Reposition()` didn't do this thoroughly, so rapid seeking left undrained output and the next `ProcessInput` failed with `MF_E_NOTACCEPTING`. NAudio 3 reworked `MediaFoundationTransform`: `Reposition()` now fully drains the transform and re-initializes streaming with an explicit `MFT_MESSAGE_COMMAND_FLUSH`, and the read loop drains output after each input. This should resolve the rapid-seek exception. Closing as fixed in NAudio 3 — please reopen if you can still reproduce it on a current build. (As an aside, `WdlResamplingSampleProvider`, which you found worked, is a fine fully-managed alternative that avoids MF entirely.)
