### ISSUE TITLE
NAudio 2.0 GetAsioDriverNames() not working

### ISSUE THREAD

**Issue by JimBayne** [naudio/NAudio#865]
I am trying to upgrade from NAudio 1.9 to 2.0.

I have the following VB code which has been working for many years ...

Dim AsioDriver() As String
...
AsioDriver = AsioOut.GetDriverNames()

but is now failing with ...

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Win32.Registry, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at NAudio.Wave.Asio.AsioDriver.GetAsioDriverNames()
   at NAudio.Wave.AsioOut.GetDriverNames() in D:\$MySoftware\VBasicStuff\$GuitarAmigo\$NAudio 2.0\Current Stuff (Includes My Fixes)\NAudio-2.0.0\NAudio.Asio\AsioOut.cs:line 117
   at BelugaBoy.Music.GA_Audio.AsioIn_GetDriverNames() in D:\$MySoftware\VBasicStuff\$GuitarAmigoNEXT\GuitarAmigo\Music\GA_Audio.vb:line 700
   at BelugaBoy.Music.GA_Audio.GetSystemAudioDeviceInfo() in D:\$MySoftware\VBasicStuff\$GuitarAmigoNEXT\GuitarAmigo\Music\GA_Audio.vb:line 637
   at BelugaBoy.Music.GA_Audio.Initialize(Object StartUpFormInst, ComboBox AudioInDeviceCB, ComboBox AudioOutDeviceCB, TunerAdjustAudioDisplayDelegateType TunerAdjustAudioDisplayDlgt, MidiEditor MidiEditorInstance, MidiEditorUpdateDelegateType MidiEditorUpdateDlgt, Sequencer SequencerInstance, AudioOut_PlayDelegateType AudioOut_PlayDlgt) in D:\$MySoftware\VBasicStuff\$GuitarAmigoNEXT\GuitarAmigo\Music\GA_Audio.vb:line 4634
   at BelugaBoy.GuitarAmigo.StartUpForm.Initialize() in D:\$MySoftware\VBasicStuff\$GuitarAmigoNEXT\GuitarAmigo\StartUpForm.vb:line 937

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Win32.Registry, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///D:/$MySoftware/VBasicStuff/$GuitarAmigoNEXT/GuitarAmigo/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : NAudio.Asio, Version=2.0.0.0, Culture=neutral, PublicKeyToken=e279aa5131008a41.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: D:\$MySoftware\VBasicStuff\$GuitarAmigoNEXT\GuitarAmigo\bin\Debug\GuitarAmigo.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Win32.Registry, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///D:/$MySoftware/VBasicStuff/$GuitarAmigoNEXT/GuitarAmigo/bin/Debug/Microsoft.Win32.Registry.DLL.
LOG: Attempting download of new URL file:///D:/$MySoftware/VBasicStuff/$GuitarAmigoNEXT/GuitarAmigo/bin/Debug/Microsoft.Win32.Registry/Microsoft.Win32.Registry.DLL.
LOG: Attempting download of new URL file:///D:/$MySoftware/VBasicStuff/$GuitarAmigoNEXT/GuitarAmigo/bin/Debug/Microsoft.Win32.Registry.EXE.
LOG: Attempting download of new URL file:///D:/$MySoftware/VBasicStuff/$GuitarAmigoNEXT/GuitarAmigo/bin/Debug/Microsoft.Win32.Registry/Microsoft.Win32.Registry.EXE.

Any assistance would be appreciated

**Comment by markheath** [comment]
Not seen that myself, but perhaps you have this problem: https://stackoverflow.com/questions/57318034/error-could-not-load-file-or-assembly-microsoft-win32registry-from-net-stand

In which case, try the solution suggested there

**Comment by JimBayne** [comment]
Sorry - user error. I now have V2.1.0 working.

**Comment by JimBayne** [comment]
Sorry - user error. I now have V2.1.0 working.
