### ISSUE TITLE
WasapiOut playThread should be set to be a background thread. 

### ISSUE THREAD

**Issue by JohnMayEko** [naudio/NAudio#891]
Application won't die!

**Comment by yatsenchee** [comment]
I have same issue, which cause my app crash
App.OnUnhandledException | System.NullReferenceException: Object reference not set to an instance of an object.
   at NAudio.Wave.WasapiOut.PlayThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by rdyhalt** [comment]
@yatsenchee

`_out.Play()` is not at blocking methode.

When `_out` goes out of scope in try-catch, it is cleanup by GC.

Try wait for PlaybackStopped event, before going forward in code.

**Comment by rdyhalt** [comment]
WasapiOut PlayThread is set to backgound thread.

See https://github.com/naudio/NAudio/blob/f8568cd4ad20c0683389cc9bc878beb945528047/NAudio.Wasapi/WasapiOut.cs#L328

**Comment by markheath** [comment]
The original request is already done — `WasapiOut`'s playback thread is created with `IsBackground = true`, so it won't keep your application alive. 

@yatsenchee's `NullReferenceException` is a separate issue: `Play()` returns immediately (it's non-blocking), so in your `try/catch` the `WasapiOut`/`AudioFileReader` can be disposed or garbage-collected while the play thread is still running, which faults `PlayThread()`. Keep a long-lived reference to the player and only dispose it from the `PlaybackStopped` handler (which your code does) — don't let it fall out of scope right after `Play()`. For new code, NAudio 3's `WasapiPlayer` is the recommended replacement for `WasapiOut`, with cleaner async teardown.

Closing as resolved — the play thread is already a background thread.
