### ISSUE TITLE
crash when NAudio.Wave.DirectSoundOut.Dispose

### ISSUE THREAD

**Issue by xiejiang2014** [naudio/NAudio#896]
.net 5 
NAudio  2.0.1

.net 5+ doesn't seem to support Thread.Abort()

Detail:

Exception Type:
System.PlatformNotSupportedException

Message:
Thread abort is not supported on this platform.

StackTrace:
   at System.Threading.Thread.Abort()
   at NAudio.Wave.DirectSoundOut.Stop()
   at NAudio.Wave.DirectSoundOut.Dispose()

**Comment by markheath** [comment]
it's hard to reproduce as the Thread.Abort only gets called in an error scenario. I'll consider removing it.
But really I'd recommend using `WasapiOut` or `WaveOutEvent` going forwards unless there is some reason you really need Direct Sound

**Comment by markheath** [comment]
Closing this as `Thread.Abort` is no longer called. For NAudio 3, the recommended playback class is now `WasapiPlayer`
