### ISSUE TITLE
'System.InvalidCastException' occurred in CSCore. Unable to cast object of type 'NAudio.CoreAudioApi.Interfaces.MMDeviceEnumeratorComObject' to type 'MMDeviceEnumeratorObject'.

### ISSUE THREAD

**Issue by agaertner** [naudio/NAudio#902]
Hello, I am reviving an old project of mine and the code that this issue is occuring worked before.

The project is a module for a framework. Said framework has abandoned CSCore and is just using NAudio now (NAudio.Core, NAudio.Wasapi). My module still relies on it though.

The error occurs at the initialize() call in the following code snippet:

```csharp
       private void Play(IWaveSource source) {
            if (source == null) return;
            var outputDevice = new WasapiOut(){ Latency = 100 };

            #if DEBUG
            outputDevice.Stopped += (o, e) => {
                if (!e.HasError) return;
                Logger.Warn(e.Exception.Message);
            };
            #endif

            var fadeStrategy = new LinearFadeStrategy(){ SampleRate = source.WaveFormat.SampleRate, Channels = source.WaveFormat.Channels };
            _fadeInOut = new FadeInOut(source.ToSampleSource()){FadeStrategy = fadeStrategy};
            _biQuadFilter = new BiQuadFilterSource(_fadeInOut) { Filter = new LowpassFilter(source.WaveFormat.SampleRate, 400) };
            _equalizer = Equalizer.Create10BandEqualizer(_biQuadFilter);

            var finalSource = _equalizer
                    .ToStereo()
                    .ChangeSampleRate(source.WaveFormat.SampleRate)
                    .ToWaveSource(source.WaveFormat.BitsPerSample);

            outputDevice.Initialize(finalSource); // InvalidCastException (see title) here.
            _initialized = true;

            _outputDevice = outputDevice;

            // Restore previous sound effects.
            SetVolume(ModuleInstance.MasterVolume);

            Fade(0, 1, TimeSpan.FromSeconds(_fadeSeconds));
            _outputDevice.Play();

        }
```

Stacktrace

```
   at CSCore.CoreAudioAPI.MMDeviceEnumerator.CreateMmDeviceEnumerator()
   at CSCore.CoreAudioAPI.MMDeviceEnumerator..ctor()
   at CSCore.CoreAudioAPI.MMDeviceEnumerator.DefaultAudioEndpoint(DataFlow dataFlow, Role role)
   at CSCore.SoundOut.WasapiOut.get_Device()
   at CSCore.SoundOut.WasapiOut.InitializeInternal()
   at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)
   at Nekres.Music_Mixer.Core.Player.Soundtrack.Play(IWaveSource source) in I:\Repositories\github.com\Blish-HUD-Modules-Releases\Music Mixer Module\Core\Player\Soundtrack.cs:line 195
   at Nekres.Music_Mixer.Core.Player.Soundtrack.<>c__DisplayClass15_0.<.ctor>b__2(Task`1 response) in I:\Repositories\github.com\Blish-HUD-Modules-Releases\Music Mixer Module\Core\Player\Soundtrack.cs:line 52
   at System.Threading.Tasks.Task.Execute()
```

**Comment by markheath** [comment]
That stack trace is entirely CSCore code. Doesn't look like you're using NAudio at all.

**Comment by agaertner** [comment]
I wanted to add that my module of course still relies on CSCore. Seems like I forgot to add that sentence. Of course it is fully CSCore.

**Comment by markheath** [comment]
I see. The exception in the issue title shows that somewhere you are trying to cast an object from CSCore into one from NAudio, which unfortunately will not work.

**Comment by agaertner** [comment]
I checked all WaveSources and all definitions none are in the NAudio namespace.

**Comment by agaertner** [comment]
![image](https://user-images.githubusercontent.com/13819164/168474154-92d48ec3-44a1-439d-b2d3-c0a0214471d1.png)

**Comment by agaertner** [comment]
Ok I tried getting the default device myself before Initialize.

Still getting it

```csharp

        private void Play(IWaveSource source) {
            if (source == null) return;
            var device = MMDeviceEnumerator.TryGetDefaultAudioEndpoint(DataFlow.Render, Role.Console); //same error here
            if (device == null) return;
            var outputDevice = new WasapiOut { Latency = 100, Device = device};

            #if DEBUG
            outputDevice.Stopped += (o, e) => {
                if (!e.HasError) return;
                Logger.Warn(e.Exception.Message);
            };
            #endif

            var fadeStrategy = new LinearFadeStrategy { SampleRate = source.WaveFormat.SampleRate, Channels = source.WaveFormat.Channels };
            _fadeInOut = new FadeInOut(source.ToSampleSource()){FadeStrategy = fadeStrategy};
            _biQuadFilter = new BiQuadFilterSource(_fadeInOut) { Filter = new LowpassFilter(source.WaveFormat.SampleRate, 400) };
            _equalizer = Equalizer.Create10BandEqualizer(_biQuadFilter);

            var finalSource = _equalizer
                    .ToStereo()
                    .ChangeSampleRate(source.WaveFormat.SampleRate)
                    .ToWaveSource(source.WaveFormat.BitsPerSample);


             outputDevice.Initialize(finalSource);
            _initialized = true;

            _outputDevice = outputDevice;

            // Restore previous sound effects.
            SetVolume(ModuleInstance.MasterVolume);

            Fade(0, 1, TimeSpan.FromSeconds(_fadeSeconds));
            _outputDevice.Play();

        }
```

**Comment by agaertner** [comment]
Moved https://github.com/filoe/cscore/issues/468
